# Good testing, this saved as a python file "scrape_to_sql" and creates the data under data/SPX_Constituents.sqlite

In [1]:
from bs4 import BeautifulSoup as bs
import numpy as np
import pandas as pd
import datetime as dt

In [16]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'


tables = pd.read_html(url, header=0)[0]
print(tables)

                            Security Symbol SEC filings  \
0                         3M Company    MMM     reports
1                Abbott Laboratories    ABT     reports
2                        AbbVie Inc.   ABBV     reports
3                        ABIOMED Inc   ABMD     reports
4                      Accenture plc    ACN     reports
5                Activision Blizzard   ATVI     reports
6                  Adobe Systems Inc   ADBE     reports
7         Advanced Micro Devices Inc    AMD     reports
8                 Advance Auto Parts    AAP     reports
9                           AES Corp    AES     reports
10     Affiliated Managers Group Inc    AMG     reports
11                         AFLAC Inc    AFL     reports
12          Agilent Technologies Inc      A     reports
13      Air Products & Chemicals Inc    APD     reports
14           Akamai Technologies Inc   AKAM     reports
15              Alaska Air Group Inc    ALK     reports
16                    Albemarle Corp    ALB     reports
17   Alexandria Real Estate Equities    ARE     reports
18           Alexion Pharmaceuticals   ALXN     reports
19                  Align Technology   ALGN     reports
20                          Allegion   ALLE     reports
21                     Allergan, Plc    AGN     reports
22             Alliance Data Systems    ADS     reports
23               Alliant Energy Corp    LNT     reports
24                     Allstate Corp    ALL     reports
25              Alphabet Inc Class A  GOOGL     reports
26              Alphabet Inc Class C   GOOG     reports
27                  Altria Group Inc     MO     reports
28                   Amazon.com Inc.   AMZN     reports
29                       Ameren Corp    AEE     reports
..                               ...    ...         ...
475                      Viacom Inc.   VIAB     reports
476                        Visa Inc.      V     reports
477             Vornado Realty Trust    VNO     reports
478                 Vulcan Materials    VMC     reports
479               Wabtec Corporation    WAB     reports
480                          Walmart    WMT     reports
481         Walgreens Boots Alliance    WBA     reports
482          The Walt Disney Company    DIS     reports
483            Waste Management Inc.     WM     reports
484               Waters Corporation    WAT     reports
485             Wec Energy Group Inc    WEC     reports
486                         WellCare    WCG     reports
487                      Wells Fargo    WFC     reports
488                   Welltower Inc.   WELL     reports
489                  Western Digital    WDC     reports
490                 Western Union Co     WU     reports
491                         WestRock    WRK     reports
492                     Weyerhaeuser     WY     reports
493                  Whirlpool Corp.    WHR     reports
494                    Williams Cos.    WMB     reports
495             Willis Towers Watson   WLTW     reports
496                 Wynn Resorts Ltd   WYNN     reports
497                  Xcel Energy Inc    XEL     reports
498                            Xerox    XRX     reports
499                           Xilinx   XLNX     reports
500                       Xylem Inc.    XYL     reports
501                  Yum! Brands Inc    YUM     reports
502           Zimmer Biomet Holdings    ZBH     reports
503                    Zions Bancorp   ZION     reports
504                           Zoetis    ZTS     reports

                GICS Sector                             GICS Sub Industry  \
0               Industrials                      Industrial Conglomerates
1               Health Care                         Health Care Equipment
2               Health Care                               Pharmaceuticals
3               Health Care                         Health Care Equipment
4    Information Technology                IT Consulting & Other Services
5    Communication Services                Interactive Home Entertainment
6    Information Technology                          Application Software
7    Information Technology                                Semiconductors
8    Consumer Discretionary                             Automotive Retail
9                 Utilities  Independent Power Producers & Energy Traders
10               Financials              Asset Management & Custody Banks
11               Financials                       Life & Health Insurance
12              Health Care                         Health Care Equipment
13                Materials                              Industrial Gases
14   Information Technology            Internet Services & Infrastructure
15              Industrials                                      Airlines
16                Materials                           Specialty Chemicals
17              Real Estate                                  Office REITs
18              Health Care                                 Biotechnology
19              Health Care                          Health Care Supplies
20              Industrials                             Building Products
21              Health Care                               Pharmaceuticals
22   Information Technology         Data Processing & Outsourced Services
23                Utilities                            Electric Utilities
24               Financials                 Property & Casualty Insurance
25   Communication Services                  Interactive Media & Services
26   Communication Services                  Interactive Media & Services
27         Consumer Staples                                       Tobacco
28   Consumer Discretionary            Internet & Direct Marketing Retail
29                Utilities                               Multi-Utilities
..                      ...                                           ...
475  Communication Services                        Movies & Entertainment
476  Information Technology                  Internet Software & Services
477             Real Estate                                  Office REITs
478               Materials                        Construction Materials
479             Industrials         Construction Machinery & Heavy Trucks
480        Consumer Staples                  Hypermarkets & Super Centers
481        Consumer Staples                                   Drug Retail
482  Communication Services                        Movies & Entertainment
483             Industrials           Environmental & Facilities Services
484             Health Care                      Health Care Distributors
485               Utilities                            Electric Utilities
486             Health Care                           Managed Health Care
487              Financials                             Diversified Banks
488             Real Estate                             Health Care REITs
489  Information Technology    Technology Hardware, Storage & Peripherals
490  Information Technology                  Internet Software & Services
491               Materials                               Paper Packaging
492             Real Estate                             Specialized REITs
493  Consumer Discretionary                          Household Appliances
494                  Energy            Oil & Gas Storage & Transportation
495              Financials                             Insurance Brokers
496  Consumer Discretionary                              Casinos & Gaming
497               Utilities                               Multi-Utilities
498  Information Technology    Technology Hardware, Storage & Peripherals
499  Information Technology                                Semiconductors
500             Industrials                          Industrial Machinery
501  Consumer Discretionary                                   Restaurants
502             Health Care                         Health Care Equipment
503              Financials                                Regional Banks
504             Health Care                               Pharmaceuticals

             Headquarters Location Date first added[3][4]      CIK  \
0              St. Paul, Minnesota                    NaN    66740
1          North Chicago, Illinois             1964-03-31     1800
2          North Chicago, Illinois             2012-12-31  1551152
3           Danvers, Massachusetts             2018-05-31   815094
4                  Dublin, Ireland             2011-07-06  1467373
5         Santa Monica, California             2015-08-31   718877
6             San Jose, California             1997-05-05   796343
7            Sunnyvale, California             2017-03-20     2488
8                Roanoke, Virginia             2015-07-09  1158449
9              Arlington, Virginia             1998-10-02   874761
10          Beverly, Massachusetts             2014-07-01  1004434
11               Columbus, Georgia             1999-05-28     4977
12         Santa Clara, California             2000-06-05  1090872
13         Allentown, Pennsylvania             1985-04-30     2969
14        Cambridge, Massachusetts             2007-07-12  1086222
15             Seattle, Washington             2016-05-13   766421
16          Baton Rouge, Louisiana             2016-07-01   915913
17            Pasadena, California             2017-03-20  1035443
18           Cheshire, Connecticut             2012-05-25   899866
19            San Jose, California             2017-06-19  1097149
20                 Dublin, Ireland             2013-12-02  1579241
21                 Dublin, Ireland             1999-04-12  1578845
22                    Plano, Texas             2013-12-23  1101215
23              Madison, Wisconsin             2016-07-01   352541
24   Northfield Township, Illinois             1995-07-13   899051
25       Mountain View, California             2014-04-03  1652044
26       Mountain View, California             2006-04-03  1652044
27              Richmond, Virginia                    NaN   764180
28             Seattle, Washington             2005-11-18  1018724
29             St. Louis, Missouri             1991-09-19  1002910
..                             ...                    ...      ...
475             New York, New York                    NaN  1339947
476      San Francisco, California             2009-12-21  1403161
477             New York, New York                    NaN   899689
478            Birmingham, Alabama             1999-06-30  1396009
479       Wilmerding, Pennsylvania             2019-02-27   943452
480          Bentonville, Arkansas             1982-08-31   104169
481            Deerfield, Illinois             1979-12-31  1618921
482            Burbank, California             1976-06-30  1001039
483                 Houston, Texas                    NaN   823768
484         Milford, Massachusetts                    NaN  1000697
485           Milwaukee, Wisconsin             2008-10-31   783325
486                 Tampa, Florida                   1985  1279363
487      San Francisco, California             1976-06-30    72971
488                   Toledo, Ohio             2009-01-30   766704
489             Irvine, California             2009-07-01   106040
490            Englewood, Colorado                    NaN  1365135
491             Richmond, Virginia                    NaN  1636023
492        Federal Way, Washington                    NaN   106535
493        Benton Harbor, Michigan                    NaN   106640
494                Tulsa, Oklahoma             1975-03-31   107263
495         London, United Kingdom             2016-01-05  1140536
496               Paradise, Nevada             2008-11-14  1174922
497         Minneapolis, Minnesota                    NaN    72903
498           Norwalk, Connecticut                    NaN   108772
499           San Jose, California             1999-11-08   743988
500         White Plains, New York             2011-11-01  1524472
501           Louisville, Kentucky             1997-10-06  1041061
502                Warsaw, Indiana             2001-08-07  1136869
503           Salt Lake City, Utah             2001-06-22   109380
504       Florham Park, New Jersey             2013-06-21  1555280

         Founded
0           1902
1           1888
2    2013 (1888)
3           1981
4           1989
5           2008
6           1982
7           1969
8           1932
9           1981
10          1993
11          1955
12          1999
13          1940
14          1998
15          1985
16          1994
17          1994
18          1992
19          1997
20          1908
21          1983
22          1996
23          1917
24          1931
25          1998
26          1998
27          1985
28          1994
29          1902
..           ...
475          NaN
476          NaN
477          NaN
478          NaN
479          NaN
480          NaN
481          NaN
482          NaN
483         1968
484         1958
485          NaN
486          NaN
487          NaN
488          NaN
489          NaN
490         1851
491          NaN
492          NaN
493         1911
494          NaN
495          NaN
496          NaN
497         1909
498         1906
499          NaN
500          NaN
501          NaN
502          NaN
503          NaN
504          NaN

[505 rows x 9 columns]

In [18]:
#took off index of [0] since it is above, will run faster this way.

df = tables
df.head()

##Brian - no longer need to define columns as the header is being properly read
#df.columns = ['Security','Symbol', 'SEC Filings', 'GICS Sector','GICS Sub Industry','Headquarters Location', 'Date Added', 'CIK', 'Founded' ]

,Security,Symbol,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added[3][4],CIK,Founded
0,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902
1,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABIOMED Inc,ABMD,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,Accenture plc,ACN,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [7]:
##Brian - commented out this line. Added "header=0" as a param for read_html
#df = df.drop([0])